application: gaemax
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: static/css/

- url: /imgs
  static_dir: static/imgs/

- url: /js
  static_dir: static/js/

- url: /.*
  script: app/main.py

builtins:
- datastore_admin: on